
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ScheduledSynchronizationSetting.
.Description
Create an in-memory object for ScheduledSynchronizationSetting.

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.DataShare.Models.Api20210801.ScheduledSynchronizationSetting
.Link
https://docs.microsoft.com/powershell/module/az.DataShare/new-AzDataShareScheduledSynchronizationSettingObject
#>
function New-AzDataShareScheduledSynchronizationSettingObject {
    [OutputType('Microsoft.Azure.PowerShell.Cmdlets.DataShare.Models.Api20210801.ScheduledSynchronizationSetting')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory, HelpMessage="Recurrence Interval.")]
        [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.RecurrenceInterval])]
        [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.RecurrenceInterval]
        $RecurrenceInterval,
        [Parameter(Mandatory, HelpMessage="Synchronization time.")]
        [System.DateTime]
        $SynchronizationTime,
        [Parameter(HelpMessage="The timestamp of resource creation (UTC).")]
        [System.DateTime]
        $SystemDataCreatedAt,
        [Parameter(HelpMessage="The identity that created the resource.")]
        [string]
        $SystemDataCreatedBy,
        [Parameter(HelpMessage="The type of identity that created the resource.")]
        [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.CreatedByType])]
        [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.CreatedByType]
        $SystemDataCreatedByType,
        [Parameter(HelpMessage="The type of identity that last modified the resource.")]
        [System.DateTime]
        $SystemDataLastModifiedAt,
        [Parameter(HelpMessage="The identity that last modified the resource.")]
        [string]
        $SystemDataLastModifiedBy,
        [Parameter(HelpMessage="The type of identity that last modified the resource.")]
        [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.LastModifiedByType])]
        [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.LastModifiedByType]
        $SystemDataLastModifiedByType
    )

    process {
        $Object = [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Models.Api20210801.ScheduledSynchronizationSetting]::New()

        if ($PSBoundParameters.ContainsKey('RecurrenceInterval')) {
            $Object.RecurrenceInterval = $RecurrenceInterval
        }
        if ($PSBoundParameters.ContainsKey('SynchronizationTime')) {
            $Object.SynchronizationTime = $SynchronizationTime
        }
        if ($PSBoundParameters.ContainsKey('SystemDataCreatedAt')) {
            $Object.SystemDataCreatedAt = $SystemDataCreatedAt
        }
        if ($PSBoundParameters.ContainsKey('SystemDataCreatedBy')) {
            $Object.SystemDataCreatedBy = $SystemDataCreatedBy
        }
        if ($PSBoundParameters.ContainsKey('SystemDataCreatedByType')) {
            $Object.SystemDataCreatedByType = $SystemDataCreatedByType
        }
        if ($PSBoundParameters.ContainsKey('SystemDataLastModifiedAt')) {
            $Object.SystemDataLastModifiedAt = $SystemDataLastModifiedAt
        }
        if ($PSBoundParameters.ContainsKey('SystemDataLastModifiedBy')) {
            $Object.SystemDataLastModifiedBy = $SystemDataLastModifiedBy
        }
        if ($PSBoundParameters.ContainsKey('SystemDataLastModifiedByType')) {
            $Object.SystemDataLastModifiedByType = $SystemDataLastModifiedByType
        }
        return $Object
    }
}

