
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for KustoTableDataSet.
.Description
Create an in-memory object for KustoTableDataSet.

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.DataShare.Models.Api20210801.KustoTableDataSet
.Link
https://docs.microsoft.com/powershell/module/az.DataShare/new-AzDataShareKustoTableDataSetObject
#>
function New-AzDataShareKustoTableDataSetObject {
    [OutputType('Microsoft.Azure.PowerShell.Cmdlets.DataShare.Models.Api20210801.KustoTableDataSet')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory, HelpMessage="Resource id of the kusto database.")]
        [string]
        $KustoDatabaseResourceId,
        [Parameter(HelpMessage="External tables to be excluded in the data set.")]
        [string[]]
        $TableLevelSharingPropertyExternalTablesToExclude,
        [Parameter(HelpMessage="External tables to be included in the data set.")]
        [string[]]
        $TableLevelSharingPropertyExternalTablesToInclude,
        [Parameter(HelpMessage="Materialized views to be excluded in the data set.")]
        [string[]]
        $TableLevelSharingPropertyMaterializedViewsToExclude,
        [Parameter(HelpMessage="Materialized views to be included in the data set.")]
        [string[]]
        $TableLevelSharingPropertyMaterializedViewsToInclude,
        [Parameter(HelpMessage="Tables to be excluded in the data set.")]
        [string[]]
        $TableLevelSharingPropertyTablesToExclude,
        [Parameter(HelpMessage="Tables to be included in the data set.")]
        [string[]]
        $TableLevelSharingPropertyTablesToInclude,
        [Parameter(Mandatory, HelpMessage="Kind of data set.")]
        [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.DataSetKind])]
        [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.DataSetKind]
        $Kind,
        [Parameter(HelpMessage="The timestamp of resource creation (UTC).")]
        [System.DateTime]
        $SystemDataCreatedAt,
        [Parameter(HelpMessage="The identity that created the resource.")]
        [string]
        $SystemDataCreatedBy,
        [Parameter(HelpMessage="The type of identity that created the resource.")]
        [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.CreatedByType])]
        [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.CreatedByType]
        $SystemDataCreatedByType,
        [Parameter(HelpMessage="The type of identity that last modified the resource.")]
        [System.DateTime]
        $SystemDataLastModifiedAt,
        [Parameter(HelpMessage="The identity that last modified the resource.")]
        [string]
        $SystemDataLastModifiedBy,
        [Parameter(HelpMessage="The type of identity that last modified the resource.")]
        [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.LastModifiedByType])]
        [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Support.LastModifiedByType]
        $SystemDataLastModifiedByType
    )

    process {
        $Object = [Microsoft.Azure.PowerShell.Cmdlets.DataShare.Models.Api20210801.KustoTableDataSet]::New()

        if ($PSBoundParameters.ContainsKey('KustoDatabaseResourceId')) {
            $Object.KustoDatabaseResourceId = $KustoDatabaseResourceId
        }
        if ($PSBoundParameters.ContainsKey('TableLevelSharingPropertyExternalTablesToExclude')) {
            $Object.TableLevelSharingPropertyExternalTablesToExclude = $TableLevelSharingPropertyExternalTablesToExclude
        }
        if ($PSBoundParameters.ContainsKey('TableLevelSharingPropertyExternalTablesToInclude')) {
            $Object.TableLevelSharingPropertyExternalTablesToInclude = $TableLevelSharingPropertyExternalTablesToInclude
        }
        if ($PSBoundParameters.ContainsKey('TableLevelSharingPropertyMaterializedViewsToExclude')) {
            $Object.TableLevelSharingPropertyMaterializedViewsToExclude = $TableLevelSharingPropertyMaterializedViewsToExclude
        }
        if ($PSBoundParameters.ContainsKey('TableLevelSharingPropertyMaterializedViewsToInclude')) {
            $Object.TableLevelSharingPropertyMaterializedViewsToInclude = $TableLevelSharingPropertyMaterializedViewsToInclude
        }
        if ($PSBoundParameters.ContainsKey('TableLevelSharingPropertyTablesToExclude')) {
            $Object.TableLevelSharingPropertyTablesToExclude = $TableLevelSharingPropertyTablesToExclude
        }
        if ($PSBoundParameters.ContainsKey('TableLevelSharingPropertyTablesToInclude')) {
            $Object.TableLevelSharingPropertyTablesToInclude = $TableLevelSharingPropertyTablesToInclude
        }
        if ($PSBoundParameters.ContainsKey('Kind')) {
            $Object.Kind = $Kind
        }
        if ($PSBoundParameters.ContainsKey('SystemDataCreatedAt')) {
            $Object.SystemDataCreatedAt = $SystemDataCreatedAt
        }
        if ($PSBoundParameters.ContainsKey('SystemDataCreatedBy')) {
            $Object.SystemDataCreatedBy = $SystemDataCreatedBy
        }
        if ($PSBoundParameters.ContainsKey('SystemDataCreatedByType')) {
            $Object.SystemDataCreatedByType = $SystemDataCreatedByType
        }
        if ($PSBoundParameters.ContainsKey('SystemDataLastModifiedAt')) {
            $Object.SystemDataLastModifiedAt = $SystemDataLastModifiedAt
        }
        if ($PSBoundParameters.ContainsKey('SystemDataLastModifiedBy')) {
            $Object.SystemDataLastModifiedBy = $SystemDataLastModifiedBy
        }
        if ($PSBoundParameters.ContainsKey('SystemDataLastModifiedByType')) {
            $Object.SystemDataLastModifiedByType = $SystemDataLastModifiedByType
        }
        return $Object
    }
}

